### ISSUE TITLE
[BUG]nodered-dashboard2页面无法显示，编辑Layout后无法保存

### ISSUE THREAD

**Issue by WuBingo12** [frangoteam/FUXA#2018]
首先建议增加西门子S7无法更改端口功能（plc模拟软件调试的时候特别需要修改端口）
server\runtime\devices\s7\index.js 38行 在ConnectTo连接前增加参数设置远程端口

```js
                        if (data.property.port != null && data.property.port >= 0 ){
                            s7client.SetParam(2, data.property.port);
                        }
```

增加界面修改端口功能 client\src\app\device\device-property\device-property.component.html 134行property-slot下增加property-port ***

```html
                    <div class="my-form-field" style="display: inline-block;margin-bottom: 10px;padding-left: 10px;">
                       <span>{{'device.property-port' | translate}}</span>
                       <input numberOnly [(ngModel)]="data.device.property.port" style="width: 80px" type="text">
                    </div>
```
然后我按照wiki提示的安装了nodered-dashboard2，但是无法通过教程中的路径访问，后面我调试修改了代码
server\integrations\node-red\index.js130行 增加少写的/api路径
```js
        app.use('/nodered/api', allowDashboard, RED.httpNode);
```
这样/nodered/api/dashboard就能正常访问，但是还有一个问题没有解决，希望能您能帮助解决：
<img width="1055" height="457" alt="Image" src="https://github.com/user-attachments/assets/18d04193-36ec-414b-a386-102fa1bd2ea9" />
上面的两个窗体无法点击打开，其中Open Dashboard 可以通过右键打开http://localhost:1881/nodered/api/dashboard/page1
但是Layout Editor这个窗体无法打开，如果我修改
server\integrations\node-red\index.js118行增加nodered跳过权限验证，可以直接通过http://localhost:1881/nodered访问控制面板
```js
if (req.path.includes('/dashboard') || req.baseUrl.includes('/nodered') || req.path.includes('/socket.io')) return next();
```
并设置调整UI页面路径，在server\_appdata\node-red\node_modules\@flowfuse\node-red-dashboard\nodes\config\ui_base.html文件316行showDashboardWysiwygEditor函数中，增加RED.settings.httpNodeRoot前缀
```js
const _url = new URL(`${RED.settings.httpNodeRoot}/${dashboardBasePath}/${data.path}`.replace(/\/\//g, '/'), windowUrl.origin)
```
这样能正常打开Layout Editor页面http://localhost:1881/nodered/api/dashboard/page1?edit-key=kvfr3lvv0lo&editor-path=nodered
但是修改Layout 后无法保存，发现保存的路径为 PATCH /nodered/nodered/api/dashboard/api/v1/287fb08ba6bc1372/flows 404 1.664 ms 无法访问
<img width="1366" height="553" alt="Image" src="https://github.com/user-attachments/assets/01483ffe-1a49-4bbb-9a99-c5867b0eb50e" />

请帮忙测试或者修复，万分感谢！

**Comment by MatthewReed303** [comment]
Please use English. There is a fix for the Node-Red dash in the advanced reports PR 

https://github.com/frangoteam/FUXA/pull/1996

@unocelli how is the PR review going?

**Comment by WuBingo12** [comment]
Thank you for your reply. I tested the code in the advanced reports PR，but it still doesn't work.  Have you tested whether it can be saved after modifying dashboard in the Layout Editor?

<img width="1214" height="549" alt="Image" src="https://github.com/user-attachments/assets/5d8ec9b0-06be-4f7b-9d6a-e9e433ba5d64" />
The Error is “PATCH /nodered/nodered/api/dashboard/api/v1/287fb08ba6bc1372/flows 404 2.047 ms - 200”

**Comment by MatthewReed303** [comment]
please try one of my builds here:

https://github.com/MatthewReed303/FUXA/actions/runs/18832333861

It's a API path permission issue that was fixed.

**Comment by WuBingo12** [comment]
I Download And Install the ExE  ,Then Create a New Project-> Open the Node-RED Flows->Install @flowfuse/node-red-dashboard ->Create a test flow to Dashboard 2.0 , But it still doesn't work. like the main branch ,Click 【Open Dashboard】or【Layout Editor】No response at all，【Open Dashboard】not important，【Layout Editor】is important ，thanks for Test or repair！

<img width="1276" height="72" alt="Image" src="https://github.com/user-attachments/assets/1becc6b0-91a8-4d84-bf82-786260095fe5" />

<img width="1923" height="660" alt="Image" src="https://github.com/user-attachments/assets/1d2bb2ef-6f13-44e6-baf7-6dd0fb3793e7" />

**Comment by MatthewReed303** [comment]
Try in an iframe, you can't open link from within electron

https://github.com/user-attachments/assets/531f7eab-f861-44bb-ad6e-8430062eaed8

**Comment by WuBingo12** [comment]
thanks for test，i know the iframe can display ，but【Layout Editor】is important，it can Modify the display grid to change vertical buttons to horizontal buttons ，Drag to adjust position, etc
<img width="620" height="624" alt="Image" src="https://github.com/user-attachments/assets/8887da67-2eb0-4b74-92c6-b291c469167c" />
 In the normal nodered process, the interface display layout should be adjusted after editing the process, but this function cannot be achieved now
first click 【Layout Editor】 open the UI ，Drag to adjust position, etc ，then save ！
<img width="561" height="374" alt="Image" src="https://github.com/user-attachments/assets/2f592881-4d4b-4e26-926e-6e34f94aa8e1" />

<img width="809" height="292" alt="Image" src="https://github.com/user-attachments/assets/adeeffde-b6a2-49c6-a58c-db69c17654dc" />

**Comment by MatthewReed303** [comment]
I will have to take a close look and find a work around. The problem is Node-Red runs in an iframe, iframes don't allow opening new tabs/windows from within. I will get to this in a few weeks. If you find a fix in the mean time please create a PR

**Comment by MatthewReed303** [comment]
@WuBingo12 this has now been fixed with https://github.com/frangoteam/FUXA/pull/2072
