### ISSUE TITLE
【improvement】Absolute coordinates required

### ISSUE THREAD

**Issue by hxjackcn** [frangoteam/FUXA#790]
Hi,
![2](https://user-images.githubusercontent.com/102520227/231908058-def80108-02fd-43d0-b993-83a622cb6ec3.png)
![3](https://user-images.githubusercontent.com/102520227/231908096-56edbf1e-facf-402d-a469-915bd3cb7bb6.png)

Thank you for your efforts.

**Comment by hxjackcn** [comment]
Wrong coordinates. Where the X-axis direction does not work.
![image](https://user-images.githubusercontent.com/102520227/235188962-0d8190f8-ecee-4687-9892-c79c0fa59e7b.png)

**Comment by unocelli** [comment]
Thanks, I fixed. 
Can you confirm me please?

**Comment by hxjackcn** [comment]
“Open iframe”  is very good now, but "open windows" is still the same.
