### ISSUE TITLE
FUXA does not store tagname in InfluxDB.

### ISSUE THREAD

**Issue by zplorer52** [frangoteam/FUXA#965]
FUXA does store  "devicename=Fuxa_Connection_name" in InfluxDB1.8 which is difficult identify specific tag name. How to add tag name too?
![image](https://github.com/frangoteam/FUXA/assets/40446297/d504880c-05e1-4646-a3c3-789c5d52a5e4)

Thanks.

**Comment by unocelli** [comment]
Hi, thanks for the report.
I would be very grateful if you could test a small modification and tell me if works so that I can add it to the branch.
You have to modify in `fuxa\server\runtime\storage\influxdb\index.js` the line 106-109 with
` const tags = {
  id: tag.id,
  devicename: deviceName,
  name: tag.name || tag.tagref.name
}`

**Comment by robbudge** [comment]
I get the same on InfluxDb2.0, would be nice to have  Device.Tag:Value
We use Grafana Alot and the UUID makes life hard. Nothing major though
I do think this would possibly cause issues with graphing as it looks that most items use the tags UUID as reference

**Comment by unocelli** [comment]
Hi, the tag name is available in version 1.1.15 for influxdb 2.0

**Comment by zplorer52** [comment]
> Hi, thanks for the report. I would be very grateful if you could test a small modification and tell me if works so that I can add it to the branch. You have to modify in `fuxa\server\runtime\storage\influxdb\index.js` the line 106-109 with ` const tags = { id: tag.id, devicename: deviceName, name: tag.name || tag.tagref.name }`

> 1. I have added the line as proposed but couldn't see any differences immediately.
![image](https://github.com/frangoteam/FUXA/assets/40446297/35609ad5-df84-4b3d-ae1f-16b6ec916236)

   2. After adding this line I've restarted the Influxdb1.8 service. And changed the "tagOptions" schedule and saved project in Fuxa connections. But it remains same.
   
![image](https://github.com/frangoteam/FUXA/assets/40446297/1c560e5d-a3e4-4639-9163-a37b49c27c4a)

![image](https://github.com/frangoteam/FUXA/assets/40446297/c58cbcac-e4a3-4036-8b0d-4e7def5af7c6)

**Comment by unocelli** [comment]
Hi, then you can debug it...can you tell me on set a breakpoint on  line 94 what have the array tagsValues...could be that the attribute name are missing.

**Comment by unocelli** [comment]
I assume the issue has been resolved in the meanwhile. I'm therefore going to close this issue.

**Comment by sjbailey838** [comment]
Hi there - I pulled the latest docker image for Fuxa and I'm still seeing this issue.

**Comment by unocelli** [comment]
Hi, for influxdb 2.0 the Tag name is available
```javascript
if (influxdbVersion === VERSION_18_FLUX) { 
  const tags = {
      id: tag.id,
      devicename: deviceName
  }
  ...
  dataToWrite.push({
      measurement: tag.id,
      tags,
      fields,
      timestamp: new Date(tag.timestamp || new Date().getTime())
  });
} else {
  const point = new Point(tag.id)
      .tag('id', tag.id)
      .tag('name', tag.name || tag.tagref.name)
      .tag('type', tag.type)
      .timestamp(new Date(tag.timestamp || new Date().getTime()));
```

**Comment by YannikObel** [comment]
Hi,
sadly this issue seems to persist in 1.3.0.
As i'm getting the 'type' tag, it rules out issues with the version_18_flux fallback. The name is also properly displayed in the web-ui. There seems to be a problem in the mapping of the objectname to the name tag for influxdb. 

<img width="1811" height="223" alt="Image" src="https://github.com/user-attachments/assets/b89edc1f-856c-426c-b74a-1122ab2f18e8" />

<img width="492" height="407" alt="Image" src="https://github.com/user-attachments/assets/4e576a61-a9c0-4140-b92c-40d8130dbdbd" />
